Enum "account_provider" {
    "spotify"
}

Enum "user_role" {
    "admin"
    "user"
}

Table "public"."scrobbles" {
  "id" uuid [pk, not null]
  "user_id" uuid [not null, ref: < "public"."users"."id"]
  "track_id" uuid [not null, ref: < "public"."tracks"."id"]
  "album_id" uuid [ref: < "public"."albums"."id"]
  "played_at" timestamptz [not null]
  "played_duration_ms" integer [not null]
  "skipped" boolean [not null, default: false]
  "is_imported" boolean [not null, default: false]
  "provider" account_provider [not null]

  Indexes {
    (user_id, track_id, played_at) [unique, name: "no_duplicate_scrobbles"]
  }
}

Table "public"."track_albums" {
  "track_id" uuid [not null, ref: < "public"."tracks"."id"]
  "album_id" uuid [not null, ref: < "public"."albums"."id"]
  "disc_number" integer
  "position" integer

  Indexes {
    (track_id, album_id) [pk, name: "track_albums_pk"]
  }
}

Table "public"."track_artists" {
  "track_id" uuid [not null, ref: < "public"."tracks"."id"]
  "artist_id" uuid [not null, ref: < "public"."artists"."id"]
  "is_primary" boolean [not null, default: true]
  "order" integer [not null]
  "join_phrase" text [not null]

  Indexes {
    (track_id, artist_id) [pk, name: "track_artists_pk"]
  }
}

Table "public"."artists" {
  "id" uuid [pk, not null]
  "name" text [not null]
  "mbid" text [unique]
  "image_url" text
}

Table "public"."artists_groups" {
  "member_id" uuid [not null, ref: < "public"."artists"."id"]
  "group_id" uuid [not null, ref: < "public"."artists"."id"]
  Indexes {
    (member_id, group_id) [pk, name: "artists_groups_pk"]
  }
}

Table "public"."users" {
  "id" uuid [pk, not null]
  "email" text [unique, not null]
  "username" text [unique]
  "image_url" text
  "role" user_role [not null]
  "created_at" timestamptz [not null]
}

Table "public"."tracks" {
  "id" uuid [pk, not null]
  "title" text [not null]
  "duration_ms" integer
  "mbid" text [unique]
  "isrc" text [unique]
  "explicit" boolean [not null]
}

Table "public"."accounts" {
  "id" uuid [pk, not null]
  "user_id" uuid [not null, ref: < "public"."users"."id"]
  "provider" account_provider [not null]
  "external_id" text [not null]
  "access_token" text
  "refresh_token" text
  "expires_at" integer
  "scope" text
}

Table "public"."albums" {
  "id" uuid [pk, not null]
  "artist_id" uuid [not null, ref: < "public"."artists"."id"]
  "title" text [not null]
  "release_date" date
  "image_url" text
  "mbid" text [unique]
}
